"""Add remaining changes
Revision ID: ddb9f96ddad5
Revises: a25edb7ae3bc
Create Date: 2022-05-12 14:41:30.209189
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb9f96ddad5'
down_revision = 'a25edb7ae3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###