"""Add remaining changes

Revision ID: a25edb7ae3bc
Revises: ca55906c13db
Create Date: 2022-05-12 14:23:28.645375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25edb7ae3bc'
down_revision = 'ca55906c13db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
