"""Add remaining changes

Revision ID: ddb9f96ddad5
Revises: a25edb7ae3bc
Create Date: 2022-05-12 14:41:30.209189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb9f96ddad5'
down_revision = 'a25edb7ae3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('title_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'votes', 'netflix_titles', ['title_id'], ['show_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'title_id')
    # ### end Alembic commands ###
